# Generated by Django 5.2.3 on 2025-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0002_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='joined',
            field=models.BooleanField(default=False, verbose_name='Bot Joined?'),
        ),
    ]
