# Generated by Django 5.2.3 on 2025-06-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0004_alter_meeting_bot_name_alter_meeting_join_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
