# Generated by Django 5.2.3 on 2025-07-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0005_transcript_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
