# Generated by Django 5.2.3 on 2025-07-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0006_transcript_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
