# Generated by Django 5.2.3 on 2025-08-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0008_transcriptsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='summary_audio',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='transcript_audio',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
    ]
