# Generated by Django 5.2.3 on 2025-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_meeting_app', '0009_transcript_summary_audio_transcript_transcript_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='hateful_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
